server:
  port: 8081

tracker:
  base-url: http://localhost:8080

simulator:
  defaults:
    hamster-count: 100
    sensor-count: 200
  wheelCount: 100
  tickSeconds: 1
  enterPerMinute: 0.10
  failPerMinute: 0.01
  temporaryFailShare: 0.8
  spinSecMin: 1
  spinSecMax: 30
  restSecAfterEscape: 10